currencies: list = [
    'EUR - Euro (€)', 
    'USD - US Dollar ($)',
    'GBP - British Pound Sterling (£)',
    'JPY - Japanese Yen (¥)',
    'CNY - Chinese Yuan (CN¥)',
    'HKD - Hong Kong Dollar (HK$)',
    'CAD - Canadian Dollar (CA$)',
    'AUD - Australian Dollar (AU$)',
    'BGN - Bulgarian Lev (BGN)',
    'CZK - Czech Republic Koruna (Kč)',
    'DKK - Danish Krone (Dkr)',
    'HUF - Hungarian Forint (Ft)',
    'PLN - Polish Zloty (zł)',
    'RON - Romanian Leu (RON)',
    'SEK - Swedish Krona (Skr)',
    'CHF - Swiss Franc (CHF)',
    'ISK - Icelandic Króna (Ikr)',
    'NOK - Norwegian Krone (Nkr)',
    'HRK - Croatian Kuna (kn)',
    'RUB - Russian Ruble (RUB)',
    'TRY - Turkish Lira (TL)',
    'BRL - Brazilian Real (R$)',
    'IDR - Indonesian Rupiah (Rp)',
    'ILS - Israeli New Sheqel (₪)',
    'INR - Indian Rupee (Rs)',
    'KRW - South Korean Won (₩)',
    'MXN - Mexican Peso (MX$)',
    'MYR - Malaysian Ringgit (RM)',
    'NZD - New Zealand Dollar (NZ$)',
    'PHP - Philippine Peso (₱)',
    'SGD - Singapore Dollar (S$)',
    'THB - Thai Baht (฿)',
    'ZAR - South African Rand (R)'
]